version: 2.1

jobs:
  build:
    working_directory: "/home/circleci/elixir_app"
    docker: 
      - image: cimg/elixir:1.13.4
    steps:
      - run:
          name: "current directory"
          command: pwd
      - run:
          name: "current files"
          command: ls -a
      - run: chown -R $USER:$USER .
      - checkout:
          path: "/home/circleci/elixir_app"
       - run:
          name: "current directory 2"
          command: pwd
      - run:
          name: "current files 2 "
          command: ls -a
      - run: mix local.hedx --force
      - run: mix loca.rebar --force
      - run: mix.deps
      - run: MIX_ENV=test mix test
      - run:
          name: Check formatted code
          command: mix format --check-formatted