version: 2.1
orbs:
  eb: circleci/aws-elastic-beanstalk@2.0.1

jobs:
  build:
    working_directory: "/home/circleci/elixir_app"
    docker: 
      - image: cimg/elixir:1.13.4
    steps:    
      - run: chown -R $USER:$USER .
      - checkout:
          path: "/home/circleci/elixir_app"
      - run:
          name: "current directory"
          command: pwd
      - run:
          name: "current files"
          command: ls -a
      - run: mix local.hex --force
      - run: mix deps.get
      - run: mix local.rebar --force
    
      - run: MIX_ENV=test mix test
      - run:
          name: Check formatted code
          command: mix format --check-formatted
          
workflows:
  elastic-beanstalk-workflow:
    jobs:
      - build
      - eb/deploy:
          context: aws-creds
          environment-name: elix4-env
          application-name: elix4-app
          filters:
            branches:
              only:
                - main
          requires:
            - build